var people = [
    "Alexandre",
    "Antoine",
    "Arthur",
    "Aurélie",
    "Aymeric",
    "Benjamin",
    "Chabane",
    "Clara",
    "Clément",
    "David",
    "Dominique",
    "Emma",
    "Fatima",
    "Florian",
    "Fred",
    "Jean",
    "Julie",
    "Kevin",
    "Vixsty",
    "Kevin M",
    "Laurent",
    "Matthieu",
    "Michaël",
    "Nicolas B",
    "Nicolas M",
    "Agent K",
    "Olivier",
    "Pascal",
    "Sebastien",
    "Théo",
    "Xavier",
    "Yohann",
];